### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by OpenBrazil** [codeforamerica/brigade#526]
Running the comand line: python manage.py runserver
I got the error:

Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from brigade import create_app
  File "C:\dev\cfbr\brigade\brigade\__init__.py", line 6, in <module>
    from sitemap import sitemap_blueprint
  File "C:\Users\coders-dev\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sitemap\__init__.py", line 172
    os.mkdir(urlset_path, 0755)
                             ^
SyntaxError: invalid token

**Comment by tdooner** [comment]
Hello! Can you try running the site with Python 2.7 and see if that works better?

**Comment by OpenBrazil** [comment]
Great! It works! Thank you!
